//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRABAJO_FINAL {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TRABAJO_FINAL.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alquilado.
        /// </summary>
        internal static string Alquilado {
            get {
                return ResourceManager.GetString("Alquilado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alquiler.
        /// </summary>
        internal static string Alquiler {
            get {
                return ResourceManager.GetString("Alquiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alquileres Ordenados.
        /// </summary>
        internal static string Alquileres_Ordenados {
            get {
                return ResourceManager.GetString("Alquileres_Ordenados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        internal static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string btnAgregar {
            get {
                return ResourceManager.GetString("btnAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string btnAgregarXml {
            get {
                return ResourceManager.GetString("btnAgregarXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alta.
        /// </summary>
        internal static string btnAlta {
            get {
                return ResourceManager.GetString("btnAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Baja.
        /// </summary>
        internal static string btnBaja {
            get {
                return ResourceManager.GetString("btnBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar datos nuevamente.
        /// </summary>
        internal static string btnCargar {
            get {
                return ResourceManager.GetString("btnCargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descartar cambios.
        /// </summary>
        internal static string btnDescartar {
            get {
                return ResourceManager.GetString("btnDescartar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grabar cambios en Base de datos.
        /// </summary>
        internal static string btnGrabar {
            get {
                return ResourceManager.GetString("btnGrabar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        internal static string btnLimpiar {
            get {
                return ResourceManager.GetString("btnLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        internal static string btnModificar {
            get {
                return ResourceManager.GetString("btnModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar.
        /// </summary>
        internal static string btnMostrarXml {
            get {
                return ResourceManager.GetString("btnMostrarXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        internal static string btnNuevo {
            get {
                return ResourceManager.GetString("btnNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte A.
        /// </summary>
        internal static string btnReporteA {
            get {
                return ResourceManager.GetString("btnReporteA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte B.
        /// </summary>
        internal static string btnReporteB {
            get {
                return ResourceManager.GetString("btnReporteB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte C.
        /// </summary>
        internal static string btnReporteC {
            get {
                return ResourceManager.GetString("btnReporteC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de Personas.
        /// </summary>
        internal static string Cantidad_de_Personas {
            get {
                return ResourceManager.GetString("Cantidad_de_Personas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Clave {
            get {
                return ResourceManager.GetString("Clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo del Cliente.
        /// </summary>
        internal static string Codigo_del_Cliente {
            get {
                return ResourceManager.GetString("Codigo_del_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Producto.
        /// </summary>
        internal static string CodigoProd {
            get {
                return ResourceManager.GetString("CodigoProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultas Sobre la BD para obetener información.
        /// </summary>
        internal static string Consultas {
            get {
                return ResourceManager.GetString("Consultas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string Correo {
            get {
                return ResourceManager.GetString("Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dias.
        /// </summary>
        internal static string Dias {
            get {
                return ResourceManager.GetString("Dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DNI.
        /// </summary>
        internal static string DNI {
            get {
                return ResourceManager.GetString("DNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DNI Cliente.
        /// </summary>
        internal static string DNI_Cliente {
            get {
                return ResourceManager.GetString("DNI_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        internal static string Entrar {
            get {
                return ResourceManager.GetString("Entrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Nacimiento.
        /// </summary>
        internal static string Fecha_de_Nacimiento {
            get {
                return ResourceManager.GetString("Fecha_de_Nacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar.
        /// </summary>
        internal static string Filtrar {
            get {
                return ResourceManager.GetString("Filtrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe.
        /// </summary>
        internal static string Importe {
            get {
                return ResourceManager.GetString("Importe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Mod o Baja).
        /// </summary>
        internal static string ModoBaja {
            get {
                return ResourceManager.GetString("ModoBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto Recaudado.
        /// </summary>
        internal static string Monto_Recaudado {
            get {
                return ResourceManager.GetString("Monto_Recaudado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        internal static string Registrar {
            get {
                return ResourceManager.GetString("Registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string Salir {
            get {
                return ResourceManager.GetString("Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño.
        /// </summary>
        internal static string Tamaño {
            get {
                return ResourceManager.GetString("Tamaño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        internal static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string Usu {
            get {
                return ResourceManager.GetString("Usu", resourceCulture);
            }
        }
    }
}
